services:

  # OCR-D Manager

  ocrd-manager:
    extends:
      file: _modules/ocrd_manager/docker-compose.yml
      service: ocrd-manager
    depends_on:
      - ocrd-controller
      - ocrd-database
    build:
      args:
        VERSION: ${MANAGER_BASE_VERSION}

  ocrd-monitor:
    extends:
      file: _modules/ocrd_monitor/docker-compose.yml
      service: ocrd-monitor
    depends_on:
      - ocrd-database

  ocrd-logview:
    extends:
      file: _modules/ocrd_monitor/docker-compose.yml
      service: ocrd-logview

  ocrd-database:
    extends:
      file: _modules/ocrd_monitor/docker-compose.yml
      service: ocrd-database

  ocrd-database-management:
    extends:
      file: _modules/ocrd_monitor/docker-compose.yml
      service: ocrd-database-management
    depends_on:
      ocrd-database:
        condition: service_started

  # OCR-D Controller

  ocrd-controller:
    extends:
      file: _modules/ocrd_controller/docker-compose.yml
      service: ocrd-controller
    profiles:
      - with-ocrd-controller
    build:
      args:
        VERSION: ${CONTROLLER_BASE_VERSION}

  # Kitodo.Production

  kitodo-app:
    extends:
      file: _modules/kitodo-production-docker/kitodo-services.yml
      service: kitodo-app
    profiles:
      - with-kitodo-production

    build:
        args:
            BUILDER_TYPE: git
            BUILDER_GIT_REF: ${APP_BUILDER_GIT_REF}
            BUILDER_GIT_REPOSITORY: ${APP_BUILDER_GIT_REPOSITORY}

    environment:
      APP_FOOTER_INFO: "Repository: <a href=\"https://github.com/${APP_BUILDER_GIT_REPOSITORY}/\">${APP_BUILDER_GIT_REPOSITORY}</a>, Ref: <a href=\"https://github.com/${APP_BUILDER_GIT_REPOSITORY}/tree/${APP_BUILDER_GIT_REF}\">${APP_BUILDER_GIT_REF}</a>"
      GIT_REF: ${APP_BUILDER_GIT_REF}
      GIT_REPOSITORY: ${APP_BUILDER_GIT_REPOSITORY}
      OCRD_MANAGER: "${MANAGER_HOST}:22"

    depends_on:
      - kitodo-db
      - kitodo-es
      - kitodo-mq
      - ocrd-manager

    volumes:
      - type: bind
        source: ${APP_KEY}
        target: /id_rsa
      - type: bind
        source: ./kitodo/before_startup.sh
        target: /usr/bin/before_startup.sh
      - type: bind
        source: ./kitodo/overwrites/sql/kitodo_post_init.sql
        target: /tmp/kitodo/overwrites/sql/post_init.sql
      - type: bind
        source: ./kitodo/overwrites/data
        target: /tmp/kitodo/overwrites/data
      - ${APP_DATA}:/usr/local/kitodo
      - ${MANAGER_WORKFLOWS}:/usr/local/ocrd-manager/workflows

  kitodo-db:
    extends:
      file: _modules/kitodo-production-docker/kitodo-services.yml
      service: kitodo-db
    profiles:
      - with-kitodo-production

  kitodo-es:
    extends:
      file: _modules/kitodo-production-docker/kitodo-services.yml
      service: kitodo-es
    profiles:
      - with-kitodo-production

  kitodo-mq:
    extends:
      file: _modules/kitodo-production-docker/kitodo-services.yml
      service: kitodo-mq
    profiles:
      - with-kitodo-production

volumes:
  db-volume:
  shared:
