services:

  # OCR-D Manager

  ocrd-manager:
    extends:
      file: _modules/ocrd_manager/docker-compose.yml
      service: ocrd-manager
    depends_on:
      - ocrd-controller

  ocrd-monitor:
    extends:
      file: _modules/ocrd_manager/ocrd_monitor/docker-compose.yml
      service: ocrd-monitor

  dozzle:
    extends:
      file: _modules/ocrd_manager/ocrd_monitor/docker-compose.yml
      service: dozzle

  # OCR-D Controller

  ocrd-controller:
    extends:
      file: _modules/ocrd_controller/docker-compose.yml
      service: ocrd-controller
    profiles:
      - with-ocrd-controller

  # Kitodo.Production

  kitodo-app:
    extends:
      file: _modules/kitodo-production-docker/kitodo/kitodo-services.yml
      service: kitodo-app
    profiles:
      - with-kitodo-production

    build:
        args:
            BUILDER_TYPE: git
            BUILDER_GIT_COMMIT: ${APP_BUILDER_GIT_COMMIT}
            BUILDER_GIT_SOURCE_URL: ${APP_BUILDER_GIT_SOURCE_URL}

    environment:
      - "OCRD_MANAGER=${MANAGER_HOST}:22"

    depends_on:
      - kitodo-db
      - kitodo-es
      - kitodo-mq
      - ocrd-manager

    volumes:
      - type: bind
        source: ${APP_KEY}
        target: /id_rsa
      - type: bind
        source: ./_resources/kitodo_post_init.sql
        target: /tmp/kitodo/overwrites/sql/post_init.sql
      - type: bind
        source: ./_resources/data
        target: /tmp/kitodo/overwrites/data
      - ${APP_DATA}:/usr/local/kitodo


  kitodo-db:
    extends:
      file: _modules/kitodo-production-docker/kitodo/kitodo-services.yml
      service: kitodo-db
    profiles:
      - with-kitodo-production

  kitodo-es:
    extends:
      file: _modules/kitodo-production-docker/kitodo/kitodo-services.yml
      service: kitodo-es
    profiles:
      - with-kitodo-production

  kitodo-mq:
    extends:
      file: _modules/kitodo-production-docker/kitodo/kitodo-services.yml
      service: kitodo-mq
    profiles:
      - with-kitodo-production

    # TODO add resource to kitodo active mq image
    volumes:
       - type: bind
         source: ./_modules/kitodo-production-docker/kitodo/kitodo-activemq.xml
         target: /opt/activemq/conf/activemq.xml

volumes:
  shared:
