version: "3.9"
services:

  ocrd-manager:
    build: 
      context: _modules/ocrd_manager
      dockerfile: Dockerfile
    
    image: ${MANAGER_IMAGE}:${MANAGER_IMAGE_TAG}

    hostname: ${MANAGER_HOST}

    environment:
      - UID=${MANAGER_ENV_UID}
      - GID=${MANAGER_ENV_GID}
      - UMASK=${MANAGER_ENV_UMASK}
      - "CONTROLLER=${CONTROLLER_HOST}:22"
      - "ACTIVEMQ=kitodo-mq:61616"
      
    ports:
        - ${MANAGER_PORT_SSH}:22

    depends_on:
      - ocrd-controller

    volumes:
        - type: bind
          source: ./ocrd/manager/.ssh/authorized_keys # kitodo public key
          target: /authorized_keys
        - type: bind
          source: ./ocrd/manager/.ssh/id_rsa
          target: /id_rsa
        - ./kitodo/config_modules/metadata:/data # metadata directory   

    tty: true # docker run -t
      

  # kitodo-app:
  #   build: 
  #       context: ${APP_BUILD_CONTEXT}
  #       dockerfile: Dockerfile
  #       args:
  #           BUILD_RESOURCES: ${APP_BUILD_RESOURCES}
    
  #   ports:
  #       - ${APP_PORT}:8080

  #   volumes:
  #       - type: bind
  #         source: ./kitodo/.ssh/id_rsa
  #         target: /id_rsa
  #       - type: bind
  #         source: ./_resources/kitodo.sql # overwrite default 3.4.1 database
  #         target: /tmp/kitodo/kitodo.sql
  #       - ./kitodo/config_modules:/usr/local/kitodo

  #   environment:
  #       - KITODO_DB_HOST=kitodo-db
  #       - KITODO_ES_HOST=kitodo-es
  #       - KITODO_MQ_HOST=kitodo-mq
  #       - "OCRD_MANAGER=${MANAGER_HOST}:22"

  #   depends_on:
  #       - kitodo-db
  #       - kitodo-es
  #       - kitodo-mq  
      
  # kitodo-db:
  #   image: mysql:${DB_VERSION}

  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_USER_PASSWORD}

  #   ports:
  #     - ${DB_PORT}:3306


  # kitodo-es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}

  #   environment:
  #       - bootstrap.memory_lock=true
  #       - discovery.type=single-node
  #       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #       - cluster.name=kitodo
  #       - node.name=kitodo-1
  #       - xpack.security.enabled=false

  #   ports:
  #       - ${ES_REST_PORT}:9200
  #       - ${ES_NODE_PORT}:9300
          
          
  # kitodo-mq:
  #   image: markusweigelt/activemq:latest
    
  #   ports:
  #       - 61616:61616
  #       - 8161:8161
        
  #   volumes:   
  #       - type: bind
  #         source: ./_resources/kitodo-activemq.xml
  #         target: /opt/activemq/conf/activemq.xml
              