version: "3.9"
services:

  kitodo-app:
    volumes:
      - type: bind
        source: ./kitodo/.ssh/id_rsa
        target: /id_rsa
      - type: bind
        source: ./_resources/kitodo.sql # overwrite default 3.4.1 database
        target: /tmp/kitodo/kitodo.sql
      - ./kitodo/config_modules:/usr/local/kitodo

    environment:
      - KITODO_DB_HOST=kitodo-db
      - KITODO_ES_HOST=kitodo-es
      - KITODO_MQ_HOST=kitodo-mq
      - "OCRD_MANAGER=${MANAGER_HOST}:22"

    depends_on:
      - kitodo-db
      - kitodo-es
      - kitodo-mq  
      - ocrd-manager


  kitodo-mq:
    image: markusweigelt/activemq:latest
    
    ports:
      - 61616:61616
      - 8161:8161
        
    volumes:   
      - type: bind
        source: ./_resources/kitodo-activemq.xml
        target: /opt/activemq/conf/activemq.xml