name: Release Stable Pull Request

on:
  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  build-pr:
    runs-on: ubuntu-latest

    steps:      
    - name: Checkout repository and submodules of stable branch
      uses: actions/checkout@v4
      with:
        ref: stable
        submodules: recursive
        fetch-depth: 0 # fetch tags

    - name: Generate environment variables
      run: |
        date +"release_version=v%Y%m%d-stable" >> $GITHUB_ENV
        date +"release_date=%Y%m%d" >> $GITHUB_ENV

    - name: Changes to provide release
      run: |
        # Update CHANGELOG.md
        ./.github/scripts/update-changelog.sh ${{ secrets.GITHUB_TOKEN }} ${{ env.release_version }}

        # Update .env
        sed -i 's|:latest|:stable|g' .env
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: changes-for-release
        title: Release stable version ${{ env.release_version }}
        body: |
          ## Autogenerated changes (see "Files changed")

          ## Manual steps to provide new release ${{ env.release_version }} after this PR is merged
          - Navigate to https://github.com/slub/ocrd_kitodo/releases/new
          - Choose a tag "${{ env.release_version }}" and create this as new tag
          - Choose target "stable"
          - Release title "Stable Version "${{ env.release_date }}" of the integration of OCR-D and Kitodo.Production"
          - Copy changes of release from CHANGELOG.md to description
        base: stable
        branch: release-stable-version-${{ env.release_version }}
        delete-branch: true
